import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { scrapeXhsProfile } from '@/lib/xhs-scraper';
import { analyzePost } from '@/lib/ai-service';

/**
 * Check if a string looks like auto-generated placeholder content
 * that should be cleared when re-scraping.
 */
function isAutoGeneratedContent(value: string): boolean {
  if (!value) return false;
  const patterns = [
    '可能的内容方向',
    '可能的内容方向1',
    'LLM基础分析',
    '手动补充建议',
  ];
  return patterns.some((p) => value.includes(p));
}

// POST /api/accounts/[id]/scrape - Trigger scraping for an account
export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const account = await db.xhsAccount.findUnique({ where: { id } });
    if (!account) {
      return NextResponse.json(
        { success: false, error: '账号不存在' },
        { status: 404 }
      );
    }

    // Set status to scraping
    await db.xhsAccount.update({
      where: { id },
      data: { status: 'scraping', errorMessage: '' },
    });

    try {
      // Scrape the profile using multi-strategy approach
      const scrapeResult = await scrapeXhsProfile(account.xhsUrl);

      // Determine status based on whether data is partial
      const accountStatus = scrapeResult.partialData ? 'partial' : 'success';

      // Build errorMessage to store warnings if any
      let errorMessage = '';
      if (scrapeResult.warnings.length > 0) {
        errorMessage = `[部分采集] ${scrapeResult.warnings.join('; ')}`;
      }

      // Update account info
      // Smart merge: use new scrape data, but keep old data only if it's
      // real user data (not auto-generated placeholder text)
      const mergeField = (
        newVal: string | number | undefined,
        oldVal: string | number | undefined,
        fieldName: string
      ): string | number => {
        // If new value is non-empty, always use it
        if (newVal && (typeof newVal === 'number' ? newVal > 0 : newVal.trim())) {
          return newVal;
        }
        // For string fields, don't keep old value if it looks auto-generated
        if (typeof oldVal === 'string' && isAutoGeneratedContent(oldVal)) {
          return typeof newVal === 'string' ? newVal : '';
        }
        // Keep old value if it's real data
        return oldVal ?? (typeof newVal === 'number' ? 0 : '');
      };

      const updatedAccount = await db.xhsAccount.update({
        where: { id },
        data: {
          nickname: mergeField(scrapeResult.account.nickname, account.nickname, 'nickname') as string,
          xhsId: mergeField(scrapeResult.account.xhsId, account.xhsId, 'xhsId') as string,
          avatarUrl: mergeField(scrapeResult.account.avatarUrl, account.avatarUrl, 'avatarUrl') as string,
          bio: mergeField(scrapeResult.account.bio, account.bio, 'bio') as string,
          location: mergeField(scrapeResult.account.location, account.location, 'location') as string,
          followers: mergeField(scrapeResult.account.followers, account.followers, 'followers') as number,
          following: mergeField(scrapeResult.account.following, account.following, 'following') as number,
          likedCollected: mergeField(scrapeResult.account.likedCollected, account.likedCollected, 'likedCollected') as number,
          notesCount: mergeField(scrapeResult.account.notesCount, account.notesCount, 'notesCount') as number,
          status: accountStatus,
          lastScrapedAt: new Date(),
          errorMessage,
        },
      });

      // Create or update posts
      const postsCreated: number[] = [];
      for (const postData of scrapeResult.posts) {
        if (!postData.xhsPostId && !postData.title) continue;

        // Check if post already exists
        const existingPost = postData.xhsPostId
          ? await db.xhsPost.findFirst({
              where: {
                accountId: id,
                xhsPostId: postData.xhsPostId as string,
              },
            })
          : null;

        const postFields = {
          xhsPostId: (postData.xhsPostId as string) || '',
          title: (postData.title as string) || '',
          content: (postData.content as string) || '',
          coverUrl: (postData.coverUrl as string) || '',
          imageUrls: JSON.stringify(postData.imageUrls || []),
          postType: (postData.postType as string) || 'normal',
          likes: (postData.likes as number) || 0,
          comments: (postData.comments as number) || 0,
          collects: (postData.collects as number) || 0,
          shares: (postData.shares as number) || 0,
          tags: JSON.stringify(postData.tags || []),
          category: (postData.category as string) || '',
          publishDate: (postData.publishDate as string) || '',
        };

        if (existingPost) {
          await db.xhsPost.update({
            where: { id: existingPost.id },
            data: postFields,
          });
          postsCreated.push(existingPost.id as never);
        } else {
          const newPost = await db.xhsPost.create({
            data: { accountId: id, ...postFields },
          });
          postsCreated.push(newPost.id as never);
        }
      }

      // Run AI analysis on posts in background (non-blocking)
      // We'll do a few posts at a time to avoid overwhelming the API
      const postsToAnalyze = await db.xhsPost.findMany({
        where: {
          accountId: id,
          aiAnalysis: '',
        },
        take: 5,
      });

      // Fire and forget AI analysis
      for (const post of postsToAnalyze) {
        analyzePost({
          title: post.title,
          content: post.content,
          tags: JSON.parse(post.tags || '[]'),
        })
          .then(async (analysis) => {
            await db.xhsPost.update({
              where: { id: post.id },
              data: {
                aiScore: analysis.score,
                aiAnalysis: JSON.stringify({
                  titleScore: analysis.titleScore,
                  contentScore: analysis.contentScore,
                  tagScore: analysis.tagScore,
                  engagementPrediction: analysis.engagementPrediction,
                  strengths: analysis.strengths,
                  weaknesses: analysis.weaknesses,
                  suggestions: analysis.suggestions,
                }),
              },
            });
          })
          .catch((err) => {
            console.error(`AI analysis failed for post ${post.id}:`, err);
          });
      }

      return NextResponse.json({
        success: true,
        data: {
          account: updatedAccount,
          postsFound: scrapeResult.totalFound,
          postsSynced: postsCreated.length,
          warnings: scrapeResult.warnings,
          partialData: scrapeResult.partialData,
          scrapeMethod: scrapeResult.scrapeMethod,
        },
      });
    } catch (scrapeError) {
      // Update account status to error
      await db.xhsAccount.update({
        where: { id },
        data: {
          status: 'error',
          errorMessage:
            scrapeError instanceof Error
              ? scrapeError.message
              : '采集失败',
        },
      });

      throw scrapeError;
    }
  } catch (error) {
    console.error('Scraping failed:', error);
    return NextResponse.json(
      {
        success: false,
        error:
          error instanceof Error ? error.message : '采集失败，请重试',
      },
      { status: 500 }
    );
  }
}
