import { NextRequest, NextResponse } from 'next/server';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';
import { db } from '@/lib/db';
import { scrapeXhsProfile } from '@/lib/xhs-scraper';
import { analyzePost } from '@/lib/ai-service';

const SCRAPER_SERVICE_URL = 'http://localhost:3002';

function extractUserIdFromUrl(url: string): string {
  const profileMatch = url.match(
    /xiaohongshu\.com\/user\/profile\/([a-f0-9]{24}|[A-Za-z0-9_-]+)/
  );
  return profileMatch?.[1] || '';
}

function hasZaiConfig(): boolean {
  return [
    path.join(process.cwd(), '.z-ai-config'),
    path.join(homedir(), '.z-ai-config'),
    'C:\\etc\\.z-ai-config',
    '/etc/.z-ai-config',
  ].some((configPath) => {
    try {
      return existsSync(configPath);
    } catch {
      return false;
    }
  });
}

async function isScraperServiceOnline(): Promise<boolean> {
  try {
    const res = await fetch(`${SCRAPER_SERVICE_URL}/api/health`, {
      signal: AbortSignal.timeout(2500),
    });
    return res.ok;
  } catch {
    return false;
  }
}

function buildUrlOnlyScrapeResult(url: string, warnings: string[]): ScrapeResultData {
  const userId = extractUserIdFromUrl(url);

  return {
    account: { xhsId: userId },
    posts: [],
    totalFound: 0,
    scrapeMethod: 'manual_required',
    warnings,
    partialData: true,
  };
}

function normalizeCookieInput(input: string): string {
  const trimmed = input
    .trim()
    .replace(/^[Cc]ookie:\s*/, '')
    .replace(/[，,。\s]+$/g, '');

  if (!trimmed) return '';

  if (trimmed.toLowerCase().startsWith('cookie:')) {
    return trimmed.slice(trimmed.indexOf(':') + 1).trim();
  }

  try {
    const parsed = JSON.parse(trimmed);

    if (Array.isArray(parsed)) {
      return parsed
        .filter((item) => item?.name && item?.value !== undefined)
        .map((item) => `${item.name}=${item.value}`)
        .join('; ');
    }

    if (typeof parsed === 'object' && parsed) {
      if (typeof parsed.cookie === 'string') return normalizeCookieInput(parsed.cookie);
      if (typeof parsed.cookies === 'string') return normalizeCookieInput(parsed.cookies);
      if (Array.isArray(parsed.cookies)) return normalizeCookieInput(JSON.stringify(parsed.cookies));
    }
  } catch {
    // Plain Cookie header string.
  }

  return trimmed;
}

/**
 * Check if a string looks like auto-generated placeholder content
 * that should be cleared when re-scraping.
 */
function isAutoGeneratedContent(value: string): boolean {
  if (!value) return false;
  const patterns = [
    '可能的内容方向',
    '可能的内容方向1',
    'LLM基础分析',
    '手动补充建议',
  ];
  return patterns.some((p) => value.includes(p));
}

/** Smart field merge: prefer new data, keep old real data over auto-generated */
function mergeField(
  newVal: string | number | undefined,
  oldVal: string | number | undefined,
  _fieldName: string
): string | number {
  if (newVal && (typeof newVal === 'number' ? newVal > 0 : newVal.trim())) {
    return newVal;
  }
  if (typeof oldVal === 'string' && isAutoGeneratedContent(oldVal)) {
    return typeof newVal === 'string' ? newVal : '';
  }
  return oldVal ?? (typeof newVal === 'number' ? 0 : '');
}

interface ScrapeAccountData {
  nickname?: string;
  xhsId?: string;
  avatarUrl?: string;
  bio?: string;
  location?: string;
  followers?: number;
  following?: number;
  likedCollected?: number;
  notesCount?: number;
}

interface ScrapePostData {
  xhsPostId?: string;
  title?: string;
  content?: string;
  coverUrl?: string;
  imageUrls?: string[];
  videoUrl?: string;
  postType?: string;
  likes?: number;
  comments?: number;
  collects?: number;
  shares?: number;
  tags?: string[];
  category?: string;
  publishDate?: string;
  detailScrapedAt?: string;
}

interface ScrapeResultData {
  account: ScrapeAccountData;
  posts: ScrapePostData[];
  totalFound: number;
  scrapeMethod: string;
  warnings: string[];
  partialData: boolean;
}

/**
 * Try cookie-based scraping via the scraper micro-service.
 */
async function scrapeWithCookies(
  url: string,
  cookies: string
): Promise<ScrapeResultData | null> {
  try {
    // Step 1: Scrape profile
    const profileRes = await fetch(
      `${SCRAPER_SERVICE_URL}/api/scrape/profile?XTransformPort=3002`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url, cookies }),
        signal: AbortSignal.timeout(60000),
      }
    );
    const profileData = await profileRes.json();

    if (!profileData.success) {
      console.log('[ScrapeRoute] Cookie profile scrape failed:', profileData.error);
      return null;
    }

    const account = profileData.data?.account || {};
    const posts: ScrapePostData[] = profileData.data?.posts || [];
    const scrapeMethod = profileData.data?.scrapeMethod || 'cookie_api';
    const warnings = profileData.data?.warnings || [];
    const partialData = profileData.data?.partialData || false;

    if (scrapeMethod !== 'cookie_api') {
      warnings.unshift(
        'Cookie 没有通过小红书接口验证，已退回到备用采集；如果需要笔记列表，请重新复制完整登录 Cookie。'
      );
    }

    // Step 2: If we got a userId, try to get more posts
    const userId = account.xhsId || '';
    if (userId && scrapeMethod === 'cookie_api') {
      try {
        const postsRes = await fetch(
          `${SCRAPER_SERVICE_URL}/api/scrape/posts?XTransformPort=3002`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ userId, cookies, num: 30 }),
            signal: AbortSignal.timeout(30000),
          }
        );
        const postsData = await postsRes.json();

        if (postsData.success && postsData.data?.posts?.length > 0) {
          // Merge posts, dedup by xhsPostId
          const existingIds = new Set(posts.map((p: ScrapePostData) => p.xhsPostId).filter(Boolean));
          for (const post of postsData.data.posts) {
            if (!existingIds.has(post.xhsPostId)) {
              posts.push(post);
              existingIds.add(post.xhsPostId);
            }
          }
        }
      } catch (postsErr) {
        console.log('[ScrapeRoute] Cookie posts fetch failed, using profile posts only');
        warnings.push('笔记列表获取失败，仅获取到部分笔记');
      }
    }

    return {
      account,
      posts,
      totalFound: posts.length,
      scrapeMethod,
      warnings,
      partialData: partialData || posts.length === 0,
    };
  } catch (err) {
    console.error('[ScrapeRoute] Cookie scraping error:', err);
    return null;
  }
}

/**
 * Try search-based scraping via the scraper micro-service.
 */
async function scrapeWithSearch(url: string): Promise<ScrapeResultData | null> {
  try {
    const profileRes = await fetch(
      `${SCRAPER_SERVICE_URL}/api/scrape/search-profile?XTransformPort=3002`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url }),
        signal: AbortSignal.timeout(60000),
      }
    );
    const profileData = await profileRes.json();

    if (!profileData.success) {
      console.log('[ScrapeRoute] Search profile scrape failed:', profileData.error);
      return null;
    }

    const account = profileData.data?.account || {};
    const posts: ScrapePostData[] = profileData.data?.posts || [];
    const scrapeMethod = profileData.data?.scrapeMethod || 'web_search';
    const warnings = profileData.data?.warnings || [];
    const partialData = profileData.data?.partialData ?? true;

    console.log('[ScrapeRoute] search-profile result: account=', account.nickname, ', posts=', posts.length, ', method=', scrapeMethod);

    // Try to get more notes via search
    const userId = account.xhsId || '';
    const nickname = account.nickname || '';
    if (userId || nickname) {
      try {
        const notesRes = await fetch(
          `${SCRAPER_SERVICE_URL}/api/scrape/search-notes?XTransformPort=3002`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ userId, nickname }),
            signal: AbortSignal.timeout(30000),
          }
        );
        const notesData = await notesRes.json();

        if (notesData.success && notesData.data?.posts?.length > 0) {
          const existingIds = new Set(posts.map((p: ScrapePostData) => p.xhsPostId).filter(Boolean));
          for (const post of notesData.data.posts) {
            if (!existingIds.has(post.xhsPostId)) {
              posts.push(post);
              existingIds.add(post.xhsPostId);
            }
          }
        }
      } catch {
        warnings.push('笔记搜索获取失败');
      }
    }

    console.log('[ScrapeRoute] scrapeWithSearch returning: posts=', posts.length, ', totalFound=', posts.length);
    return {
      account,
      posts,
      totalFound: posts.length,
      scrapeMethod,
      warnings,
      partialData,
    };
  } catch (err) {
    console.error('[ScrapeRoute] Search scraping error:', err);
    return null;
  }
}

// POST /api/accounts/[id]/scrape - Trigger scraping for an account
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const account = await db.xhsAccount.findUnique({ where: { id } });
    if (!account) {
      return NextResponse.json(
        { success: false, error: '账号不存在' },
        { status: 404 }
      );
    }

    // Parse request body for method and cookies
    let body: { method?: string; cookies?: string } = {};
    try {
      body = await request.json();
    } catch {
      // No body or invalid JSON, use default method
    }

    const scrapeMethod = body.method || 'search'; // 'cookie' | 'search'
    const cookies = normalizeCookieInput(body.cookies || '');
    const scraperOnline = await isScraperServiceOnline();
    const zaiConfigured = hasZaiConfig();
    const preflightWarnings: string[] = [];

    if (!scraperOnline) {
      preflightWarnings.push(
        '采集服务未启动，请先运行 npm run scraper；否则只能使用基础兜底数据。'
      );
    }

    if (!zaiConfigured) {
      preflightWarnings.push(
        '搜索采集和 AI 兜底需要 .z-ai-config；没有配置时建议使用 Cookie 采集。'
      );
    }

    if (scrapeMethod === 'cookie' && !cookies.trim()) {
      return NextResponse.json(
        { success: false, error: 'Cookie 采集需要先粘贴小红书登录 Cookie。' },
        { status: 400 }
      );
    }

    // Set status to scraping
    await db.xhsAccount.update({
      where: { id },
      data: { status: 'scraping', errorMessage: '' },
    });

    try {
      let scrapeResult: ScrapeResultData | null = null;

      // Strategy 1: Cookie-based scraping (if cookies provided)
      if (scrapeMethod === 'cookie' && cookies) {
        console.log('[ScrapeRoute] Trying cookie-based scraping');
        scrapeResult = await scrapeWithCookies(account.xhsUrl, cookies);
      }

      // Strategy 2: Search-based scraping (fallback or chosen method)
      if (!scrapeResult && (scrapeMethod === 'search' || scrapeMethod === 'cookie')) {
        console.log('[ScrapeRoute] Trying search-based scraping');
        scrapeResult = await scrapeWithSearch(account.xhsUrl);
      }

      // Strategy 3: Legacy xhs-scraper (final fallback)
      if (!scrapeResult) {
        if (zaiConfigured) {
          console.log('[ScrapeRoute] Falling back to legacy scraper');
          const legacyResult = await scrapeXhsProfile(account.xhsUrl);
          scrapeResult = {
            account: legacyResult.account as ScrapeAccountData,
            posts: legacyResult.posts as ScrapePostData[],
            totalFound: legacyResult.totalFound,
            scrapeMethod: legacyResult.scrapeMethod,
            warnings: legacyResult.warnings,
            partialData: legacyResult.partialData,
          };
        } else {
          scrapeResult = buildUrlOnlyScrapeResult(account.xhsUrl, [
            '当前环境无法执行搜索采集或 AI 兜底，只保留了主页链接中的用户 ID。',
          ]);
        }
      }

      scrapeResult.warnings = [...preflightWarnings, ...scrapeResult.warnings];

      if (scrapeResult.totalFound === 0 && !cookies.trim()) {
        scrapeResult.warnings.push(
          '未采集到笔记列表。小红书笔记列表通常需要登录 Cookie，请在采集弹窗中选择 Cookie 采集。'
        );
      }

      // Batch fetch note details via scraper micro-service
      // Only for posts that have xhsPostId and lack content/images
      const postsNeedingDetails = scrapeResult.posts.filter(
        (p) => p.xhsPostId && (!p.content || p.content.length < 10) && p.postType !== 'video'
      );

      if (postsNeedingDetails.length > 0 && scraperOnline) {
        console.log(`[ScrapeRoute] Batch fetching details for ${postsNeedingDetails.length} notes`);
        const CONCURRENCY = 3;
        let detailsFetched = 0;

        for (let i = 0; i < postsNeedingDetails.length; i += CONCURRENCY) {
          const batch = postsNeedingDetails.slice(i, i + CONCURRENCY);
          const results = await Promise.allSettled(
            batch.map(async (post) => {
              try {
                const res = await fetch(`${SCRAPER_SERVICE_URL}/api/scrape/note`, {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: JSON.stringify({ noteId: post.xhsPostId, cookies: cookies || '' }),
                  signal: AbortSignal.timeout(30000),
                });
                const json = await res.json();
                if (json.success && json.data?.note) {
                  return { postId: post.xhsPostId, detail: json.data.note };
                }
                return null;
              } catch {
                return null;
              }
            })
          );

          for (const result of results) {
            if (result.status === 'fulfilled' && result.value) {
              const { postId, detail } = result.value;
              const target = scrapeResult.posts.find((p) => p.xhsPostId === postId);
              if (target && detail) {
                if (detail.content) target.content = detail.content;
                if (detail.imageUrls?.length) target.imageUrls = detail.imageUrls;
                if (detail.videoUrl) target.videoUrl = detail.videoUrl;
                if (detail.tags?.length) target.tags = detail.tags;
                if (detail.publishDate) target.publishDate = detail.publishDate;
                target.detailScrapedAt = new Date().toISOString();
                detailsFetched++;
              }
            }
          }

          // Batch delay to avoid rate limiting
          if (i + CONCURRENCY < postsNeedingDetails.length) {
            await new Promise((r) => setTimeout(r, 2000 + Math.random() * 1000));
          }
        }

        if (detailsFetched > 0) {
          scrapeResult.warnings.push(`已补充 ${detailsFetched} 条笔记详情（正文/图片/标签）`);
        }
      }

      // Determine status based on whether data is partial
      const accountStatus = scrapeResult.partialData ? 'partial' : 'success';

      // Build errorMessage to store warnings if any
      let errorMessage = '';
      if (scrapeResult.warnings.length > 0) {
        errorMessage = `[${scrapeResult.scrapeMethod === 'cookie_api' ? 'Cookie采集' : scrapeResult.scrapeMethod === 'web_search' ? '搜索采集' : '基础采集'}] ${scrapeResult.warnings.join('; ')}`;
      }

      // Update account info with smart merge
      const updatedAccount = await db.xhsAccount.update({
        where: { id },
        data: {
          nickname: mergeField(scrapeResult.account.nickname, account.nickname, 'nickname') as string,
          xhsId: mergeField(scrapeResult.account.xhsId, account.xhsId, 'xhsId') as string,
          avatarUrl: mergeField(scrapeResult.account.avatarUrl, account.avatarUrl, 'avatarUrl') as string,
          bio: mergeField(scrapeResult.account.bio, account.bio, 'bio') as string,
          location: mergeField(scrapeResult.account.location, account.location, 'location') as string,
          followers: mergeField(scrapeResult.account.followers, account.followers, 'followers') as number,
          following: mergeField(scrapeResult.account.following, account.following, 'following') as number,
          likedCollected: mergeField(scrapeResult.account.likedCollected, account.likedCollected, 'likedCollected') as number,
          notesCount: mergeField(scrapeResult.account.notesCount, account.notesCount, 'notesCount') as number,
          status: accountStatus,
          lastScrapedAt: new Date(),
          errorMessage,
        },
      });

      // Create or update posts
      const postsCreated: string[] = [];
      for (const postData of scrapeResult.posts) {
        if (!postData.xhsPostId && !postData.title) continue;

        const existingPost = postData.xhsPostId
          ? await db.xhsPost.findFirst({
              where: {
                accountId: id,
                xhsPostId: postData.xhsPostId as string,
              },
            })
          : null;

        const postFields = {
          xhsPostId: (postData.xhsPostId as string) || '',
          title: (postData.title as string) || '',
          content: (postData.content as string) || '',
          coverUrl: (postData.coverUrl as string) || '',
          imageUrls: JSON.stringify(postData.imageUrls || []),
          videoUrl: (postData.videoUrl as string) || '',
          postType: (postData.postType as string) || 'normal',
          likes: (postData.likes as number) || 0,
          comments: (postData.comments as number) || 0,
          collects: (postData.collects as number) || 0,
          shares: (postData.shares as number) || 0,
          tags: JSON.stringify(postData.tags || []),
          category: (postData.category as string) || '',
          publishDate: (postData.publishDate as string) || '',
          detailScrapedAt: postData.detailScrapedAt ? new Date(postData.detailScrapedAt) : null,
        };

        if (existingPost) {
          await db.xhsPost.update({
            where: { id: existingPost.id },
            data: postFields,
          });
          postsCreated.push(existingPost.id);
        } else {
          const newPost = await db.xhsPost.create({
            data: { accountId: id, ...postFields },
          });
          postsCreated.push(newPost.id);
        }
      }

      // Run AI analysis on posts in background (non-blocking)
      const postsToAnalyze = await db.xhsPost.findMany({
        where: {
          accountId: id,
          aiAnalysis: '',
        },
        take: 5,
      });

      for (const post of postsToAnalyze) {
        analyzePost({
          title: post.title,
          content: post.content,
          tags: JSON.parse(post.tags || '[]'),
        })
          .then(async (analysis) => {
            await db.xhsPost.update({
              where: { id: post.id },
              data: {
                aiScore: analysis.score,
                aiAnalysis: JSON.stringify({
                  titleScore: analysis.titleScore,
                  contentScore: analysis.contentScore,
                  tagScore: analysis.tagScore,
                  engagementPrediction: analysis.engagementPrediction,
                  strengths: analysis.strengths,
                  weaknesses: analysis.weaknesses,
                  suggestions: analysis.suggestions,
                }),
              },
            });
          })
          .catch((err) => {
            console.error(`AI analysis failed for post ${post.id}:`, err);
          });
      }

      return NextResponse.json({
        success: true,
        data: {
          account: updatedAccount,
          postsFound: scrapeResult.totalFound,
          postsSynced: postsCreated.length,
          warnings: scrapeResult.warnings,
          partialData: scrapeResult.partialData,
          scrapeMethod: scrapeResult.scrapeMethod,
        },
      });
    } catch (scrapeError) {
      await db.xhsAccount.update({
        where: { id },
        data: {
          status: 'error',
          errorMessage:
            scrapeError instanceof Error
              ? scrapeError.message
              : '采集失败',
        },
      });

      throw scrapeError;
    }
  } catch (error) {
    console.error('Scraping failed:', error);
    return NextResponse.json(
      {
        success: false,
        error:
          error instanceof Error ? error.message : '采集失败，请重试',
      },
      { status: 500 }
    );
  }
}
